// Map a full cover image path to its committed WebP thumbnail (generated by
// scripts/generate-thumbnails.mjs and mirrored under public/thumbs/). Used by
// the grid and Similar-tunes rail so they load small thumbnails, not full-res
// screenshots. Non-cover paths pass through unchanged.
export function thumbUrl(cover: string): string {
  return cover.startsWith('images/') ? cover.replace(/^images\//, 'thumbs/') : cover;
}
